name: CI • Backend

on:
  push:
    branches: [master]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    branches: [master]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Upgrade npm
        run: npm install -g npm@10

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build:ci

      # - name: Test
      #   run: npm run test:ci
