name: CI • Frontend & Backend

on:
  push:
    branches: [master]
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [master]
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/ci.yml"

permissions:
  contents: read

jobs:
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Upgrade npm
        run: npm install -g npm@10

      - name: Install all workspaces
        run: npm install --workspaces

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build:ci

      # - name: Test
      #   run: npm run test:ci
      #   # Optional: Enable if test:ci exists in frontend/package.json

  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Upgrade npm
        run: npm install -g npm@10

      - name: Install all workspaces
        run: npm install --workspaces

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build:ci

      # - name: Test
      #   run: npm run test:ci
      #   # Optional: Enable if test:ci exists in backend/package.json
