name: Release Version

on:
  workflow_run:
    workflows:
      - "CI • Frontend"
      - "CI • Backend"
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  release:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Upgrade npm
        run: npm install -g npm@10

      - name: Install all workspaces
        run: npm install --workspaces

      - name: Sync versions across frontend/backend
        run: node sync-version.js

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
